import { BiLogoPostgresql, BiLogoGoLang } from "react-icons/bi";
import { BsFillBootstrapFill } from "react-icons/bs";
import {
  SiApollographql,
  SiChakraui,
  SiCss3,
  SiExpo,
  SiExpress,
  SiFirebase,
  SiFramer,
  SiGithub,
  SiGraphql,
  SiGulp,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiLaravel,
  SiMui,
  SiNextdotjs,
  SiNodedotjs,
  SiNuxtdotjs,
  SiPhp,
  SiPrisma,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiReactrouter,
  SiReacttable,
  SiRedux,
  SiSass,
  SiStorybook,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiVuedotjs,
  SiWordpress,
  SiCodeigniter,
  SiMysql,
  SiFlutter,
  SiDjango,
  SiPython,
  SiDocker,
} from "react-icons/si";

type stacksProps = {
  [key: string]: JSX.Element;
};

const iconSize = "100%";

export const STACKS: stacksProps = {
  php: <SiPhp size={iconSize} className="text-blue-500" />,
  javascript: <SiJavascript size={iconSize} className="text-yellow-400" />,
  typescript: <SiTypescript size={iconSize} className="text-blue-400" />,
  "next.js": <SiNextdotjs size={iconSize} />,
  "react.js": <SiReact size={iconSize} className="text-sky-500" />,
  tailwindCSS: <SiTailwindcss size={iconSize} className="text-cyan-300" />,
  bootstrap: (
    <BsFillBootstrapFill size={iconSize} className="text-purple-500" />
  ),
  graphqL: <SiGraphql size={iconSize} className="text-pink-600" />,
  apollo: <SiApollographql size={iconSize} />,
  wordpress: <SiWordpress size={iconSize} />,
  laravel: <SiLaravel size={iconSize} className="text-red-500" />,
  "material ui": <SiMui size={iconSize} className="text-sky-400" />,
  vite: <SiVite size={iconSize} className="text-purple-500" />,
  postgresql: <BiLogoPostgresql size={iconSize} className="text-blue-400" />,
  chakraui: <SiChakraui size={iconSize} className="text-teal-500" />,
  "react native": <SiReact size={iconSize} className="text-sky-600" />,
  expo: <SiExpo size={iconSize} />,
  sass: <SiSass size={iconSize} className="text-pink-600" />,
  gulp: <SiGulp size={iconSize} className="text-red-500" />,
  firebase: <SiFirebase size={iconSize} className="text-yellow-500" />,
  "framer motion": <SiFramer size={iconSize} />,
  "nuxt.js": <SiNuxtdotjs size={iconSize} className="text-green-600" />,
  "vue.js": <SiVuedotjs size={iconSize} className="text-green-500" />,
  jest: <SiJest size={iconSize} className="text-orange-600" />,
  "express.js": <SiExpress size={iconSize} />,
  redux: <SiRedux size={iconSize} className="text-purple-500" />,
  "react Query": <SiReactquery size={iconSize} className="text-red-600" />,
  html: <SiHtml5 size={iconSize} className="text-orange-500" />,
  css: <SiCss3 size={iconSize} className="text-blue-500" />,
  prisma: <SiPrisma size={iconSize} className="text-teal-500" />,
  "node js": <SiNodedotjs size={iconSize} className="text-green-600" />,
  github: <SiGithub size={iconSize} />,
  storybook: <SiStorybook size={iconSize} className="text-pink-500" />,
  "react router": <SiReactrouter size={iconSize} className="text-pink-500" />,
  "react hook form": (
    <SiReacthookform size={iconSize} className="text-pink-500" />
  ),
  "react table": <SiReacttable size={iconSize} className="text-rose-600" />,
  codeigniter: <SiCodeigniter size={iconSize} className="text-rose-600" />,
  mysql: <SiMysql size={iconSize} className="text-blue-500" />,
  flutter: <SiFlutter size={iconSize} className="text-blue-500" />,
  golang: <BiLogoGoLang size={iconSize} className="text-blue-500" />,
  django: <SiDjango size={iconSize} className="text-teal-500" />,
  python: <SiPython size={iconSize} className="text-blue-500" />,
  docker: <SiDocker size={iconSize} className="text-blue-400" />,
};
